apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: jmeter-result
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script with the slave POD IP addresses
    #Script should be run like: ./load_test "path to the test script in jmx format"
    if [ -f /report/result.jtl ]; then
      rm /report/result.jtl
    fi
    /opt/apache-jmeter-*/bin/jmeter -n -t /$1 -l /report/result.jtl -Dserver.rmi.ssl.disable=true -R `getent ahostsv4 jmeter-slaves-svc | cut -d' ' -f1 | sort -u | awk -v ORS=, '{print $1}' | sed 's/,$//'` "${@:2:($#-1)}"
